# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vectordb_pb2 as vectordb__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vectordb_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VectorDBStub(object):
    """Collection service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpsertPoints = channel.unary_unary(
                '/vectordb.VectorDB/UpsertPoints',
                request_serializer=vectordb__pb2.UpsertPointsRequest.SerializeToString,
                response_deserializer=vectordb__pb2.UpsertPointsResponse.FromString,
                _registered_method=True)
        self.SearchPoints = channel.unary_unary(
                '/vectordb.VectorDB/SearchPoints',
                request_serializer=vectordb__pb2.SearchPointsRequest.SerializeToString,
                response_deserializer=vectordb__pb2.SearchPointsResponse.FromString,
                _registered_method=True)
        self.GetPoint = channel.unary_unary(
                '/vectordb.VectorDB/GetPoint',
                request_serializer=vectordb__pb2.GetPointRequest.SerializeToString,
                response_deserializer=vectordb__pb2.GetPointResponse.FromString,
                _registered_method=True)
        self.DeletePoint = channel.unary_unary(
                '/vectordb.VectorDB/DeletePoint',
                request_serializer=vectordb__pb2.DeletePointRequest.SerializeToString,
                response_deserializer=vectordb__pb2.DeletePointResponse.FromString,
                _registered_method=True)
        self.CreateCollection = channel.unary_unary(
                '/vectordb.VectorDB/CreateCollection',
                request_serializer=vectordb__pb2.CreateCollectionRequest.SerializeToString,
                response_deserializer=vectordb__pb2.CreateCollectionResponse.FromString,
                _registered_method=True)
        self.ListCollections = channel.unary_unary(
                '/vectordb.VectorDB/ListCollections',
                request_serializer=vectordb__pb2.ListCollectionsRequest.SerializeToString,
                response_deserializer=vectordb__pb2.ListCollectionsResponse.FromString,
                _registered_method=True)


class VectorDBServicer(object):
    """Collection service
    """

    def UpsertPoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchPoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCollections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorDBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpsertPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertPoints,
                    request_deserializer=vectordb__pb2.UpsertPointsRequest.FromString,
                    response_serializer=vectordb__pb2.UpsertPointsResponse.SerializeToString,
            ),
            'SearchPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchPoints,
                    request_deserializer=vectordb__pb2.SearchPointsRequest.FromString,
                    response_serializer=vectordb__pb2.SearchPointsResponse.SerializeToString,
            ),
            'GetPoint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPoint,
                    request_deserializer=vectordb__pb2.GetPointRequest.FromString,
                    response_serializer=vectordb__pb2.GetPointResponse.SerializeToString,
            ),
            'DeletePoint': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePoint,
                    request_deserializer=vectordb__pb2.DeletePointRequest.FromString,
                    response_serializer=vectordb__pb2.DeletePointResponse.SerializeToString,
            ),
            'CreateCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCollection,
                    request_deserializer=vectordb__pb2.CreateCollectionRequest.FromString,
                    response_serializer=vectordb__pb2.CreateCollectionResponse.SerializeToString,
            ),
            'ListCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCollections,
                    request_deserializer=vectordb__pb2.ListCollectionsRequest.FromString,
                    response_serializer=vectordb__pb2.ListCollectionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vectordb.VectorDB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vectordb.VectorDB', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VectorDB(object):
    """Collection service
    """

    @staticmethod
    def UpsertPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectordb.VectorDB/UpsertPoints',
            vectordb__pb2.UpsertPointsRequest.SerializeToString,
            vectordb__pb2.UpsertPointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectordb.VectorDB/SearchPoints',
            vectordb__pb2.SearchPointsRequest.SerializeToString,
            vectordb__pb2.SearchPointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectordb.VectorDB/GetPoint',
            vectordb__pb2.GetPointRequest.SerializeToString,
            vectordb__pb2.GetPointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectordb.VectorDB/DeletePoint',
            vectordb__pb2.DeletePointRequest.SerializeToString,
            vectordb__pb2.DeletePointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectordb.VectorDB/CreateCollection',
            vectordb__pb2.CreateCollectionRequest.SerializeToString,
            vectordb__pb2.CreateCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectordb.VectorDB/ListCollections',
            vectordb__pb2.ListCollectionsRequest.SerializeToString,
            vectordb__pb2.ListCollectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
